---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	intake(intake)
	places(places)
	weather(weather)
	generate(generate)
	modify(modify)
	validate(validate)
	finalize(finalize)
	__end__([<p>__end__</p>]):::last
	__start__ --> intake;
	generate --> validate;
	intake --> places;
	modify --> validate;
	places --> weather;
	validate -.-> finalize;
	validate -.-> generate;
	validate -.-> modify;
	weather -.-> generate;
	weather -.-> modify;
	finalize --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
